FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY data-platform/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY data-platform /opt/airflow/data-platform
ENV PYTHONPATH=/opt/airflow/data-platform
